language: node_js
node_js:
    - "lts/*"
install:
    - yarn install
script:
    - yarn docs:build
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $ArtToolsDoc_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
        branch: master