language: node_js
node_js:
    - "lts/*"
install:
    - yarn install
script:
    - yarn docs:build
notifications:
    email: false
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $ArtToolsDoc_TOKEN
    keep_history: true
    on:
        branch: master
